#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PAIR_ROOT="$SCRIPT_DIR"
VC_EDIT_REPO="${VC_EDIT_REPO:-/inspire/qb-ilm2/project/embodied-multimodality/public/xyzhang/projects/vc_edit}"
EDITX_SCRIPT="${EDITX_SCRIPT:-$VC_EDIT_REPO/vc_edit_framework/scripts/run_step_editx_split.sh}"
QZCLI="${QZCLI:-qzcli}"

SPLIT_DIR="${SPLIT_DIR:-${1:-}}"
if [ -z "${SPLIT_DIR}" ]; then
  echo "Usage: sh submit_editx_ablation_probe_h200.sh <split_dir>"
  exit 1
fi
SPLIT_DIR=$(CDPATH= cd -- "${SPLIT_DIR}" && pwd)
SPLIT_NAME=$(basename -- "${SPLIT_DIR}")

WORKSPACE="${WORKSPACE:-CI-情境智能}"
PROJECT="${PROJECT:-CI-情境智能}"
FRAMEWORK="${FRAMEWORK:-pytorch}"
IMAGE="${IMAGE:-docker.sii.shaipower.online/inspire-studio/ngc-pytorch-25.10:25_patch_20260420}"
IMAGE_TYPE="${IMAGE_TYPE:-SOURCE_PRIVATE}"
SHM_GI="${SHM_GI:-1200}"
PRIORITY="${PRIORITY:-10}"
SPEC="${SPEC:-67b10bc6-78b0-41a3-aaf4-358eeeb99009}"
INSTANCES=1

DEFAULT_MOSS_COMPUTE_GROUP="lcg-73efc9b6-8d94-406c-b150-50c91fda377f"
DEFAULT_INFRA_DEBUG_GROUP="lcg-4202c8f7-8308-412c-92b9-77daccab3c7f"
COMPUTE_GROUP="${COMPUTE_GROUP:-$DEFAULT_INFRA_DEBUG_GROUP}"

EXPERIMENT_NAME="${EXPERIMENT_NAME:-baseline}"
RUN_ID="${RUN_ID:-$(date -u +%m%d-%H%M%S)}"
JOB_NAME_PREFIX="${JOB_NAME_PREFIX:-zxy-editx-ablation}"
JOB_NAME="${JOB_NAME:-${JOB_NAME_PREFIX}-${EXPERIMENT_NAME}-${SPLIT_NAME}-${RUN_ID}}"

EDIT_TYPE="${EDIT_TYPE:-style}"
EDIT_INFO="${EDIT_INFO:-radio}"
FILTER_TAG="${FILTER_TAG:-all}"
START_INDEX="${START_INDEX:-0}"
LIMIT="${LIMIT:-0}"

MODEL_DIR="${MODEL_DIR:-$VC_EDIT_REPO/models/Step-Audio-EditX}"
TOKENIZER_DIR="${TOKENIZER_DIR:-$VC_EDIT_REPO/models/Step-Audio-Tokenizer}"
STEPX_PY="${STEPX_PY:-/inspire/ssd/project/embodied-multimodality/public/yqzhang/miniconda3/envs/step_audio_editx/bin/python}"

GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.35}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-8192}"
DTYPE="${DTYPE:-bfloat16}"
BATCH_SIZE="${BATCH_SIZE:-8}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-8}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-8}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-0}"
KV_CACHE_DTYPE="${KV_CACHE_DTYPE:-}"
PREPARE_WORKERS="${PREPARE_WORKERS:-1}"
AUDIO_CONDITION_BUILD_WORKERS="${AUDIO_CONDITION_BUILD_WORKERS:-$PREPARE_WORKERS}"
DISABLE_AUDIO_CONDITION_ITEM_PARALLEL="${DISABLE_AUDIO_CONDITION_ITEM_PARALLEL:-0}"
ASYNC_WRITE_WORKERS="${ASYNC_WRITE_WORKERS:-0}"
ASYNC_VOCODER_WORKERS="${ASYNC_VOCODER_WORKERS:-0}"
PREPARE_BREAKDOWN="${PREPARE_BREAKDOWN:-0}"
NEXT_BATCH_PREFETCH="${NEXT_BATCH_PREFETCH:-0}"
PREFETCH_DEPTH="${PREFETCH_DEPTH:-1}"
USE_ASYNC_ENGINE="${USE_ASYNC_ENGINE:-0}"
STREAM_VOCODE="${STREAM_VOCODE:-0}"
ENGINE_COUNT="${ENGINE_COUNT:-1}"
ENGINE_GPU_GROUPS="${ENGINE_GPU_GROUPS:-}"
ENGINE_JOB_SPLIT_MODE="${ENGINE_JOB_SPLIT_MODE:-round_robin}"
ENGINE_STARTUP_STAGGER_SEC="${ENGINE_STARTUP_STAGGER_SEC:-0}"
ENGINE_PER_ATTEMPT_RETRIES="${ENGINE_PER_ATTEMPT_RETRIES:-0}"
ENGINE_PER_ATTEMPT_BACKOFF_SEC="${ENGINE_PER_ATTEMPT_BACKOFF_SEC:-15}"
PREPROCESS_CACHE_SIZE="${PREPROCESS_CACHE_SIZE:-512}"
AUDIO_DURATION_BUCKETING="${AUDIO_DURATION_BUCKETING:-0}"
DURATION_BUCKET_WINDOW="${DURATION_BUCKET_WINDOW:-0}"
MAX_RUNTIME_SEC="${MAX_RUNTIME_SEC:-600}"
AUDIO_CONDITION_CACHE_DIR="${AUDIO_CONDITION_CACHE_DIR:-}"
AUDIO_CONDITION_CACHE_WRITEBACK="${AUDIO_CONDITION_CACHE_WRITEBACK:-0}"
COSYVOICE_CUDA_GRAPH="${COSYVOICE_CUDA_GRAPH:-0}"
EDITX_GPU_MONITOR_ENABLE="${EDITX_GPU_MONITOR_ENABLE:-1}"
EDITX_GPU_MONITOR_INTERVAL_SEC="${EDITX_GPU_MONITOR_INTERVAL_SEC:-10}"
DUMMY_GPU_KEEPALIVE="${DUMMY_GPU_KEEPALIVE:-0}"
DUMMY_GPU_KEEPALIVE_DEVICES="${DUMMY_GPU_KEEPALIVE_DEVICES:-}"
DUMMY_GPU_KEEPALIVE_DTYPE="${DUMMY_GPU_KEEPALIVE_DTYPE:-float16}"
DUMMY_GPU_KEEPALIVE_SIZE="${DUMMY_GPU_KEEPALIVE_SIZE:-2048}"
DUMMY_GPU_KEEPALIVE_WARMUP="${DUMMY_GPU_KEEPALIVE_WARMUP:-4}"
DUMMY_GPU_KEEPALIVE_SLEEP="${DUMMY_GPU_KEEPALIVE_SLEEP:-0.50}"

RUN_ROOT="${RUN_ROOT:-$SPLIT_DIR/ablation_runs/${EXPERIMENT_NAME}_${RUN_ID}}"
OUTPUT_DIR="${OUTPUT_DIR:-$RUN_ROOT/output}"
REPORT_JSONL="${REPORT_JSONL:-$OUTPUT_DIR/paired_report.jsonl}"
BATCH_METRICS_TSV="${BATCH_METRICS_TSV:-$OUTPUT_DIR/batch_metrics.tsv}"
SUMMARY_JSON="${SUMMARY_JSON:-$OUTPUT_DIR/run_summary.json}"
GPU_MONITOR_LOG="${GPU_MONITOR_LOG:-$OUTPUT_DIR/gpu_metrics.csv}"
JOB_RECORD_ROOT="${JOB_RECORD_ROOT:-$PAIR_ROOT/.qz_editx_ablation_probes}"
SUMMARY_TSV="${SUMMARY_TSV:-$JOB_RECORD_ROOT/submitted_jobs.tsv}"

mkdir -p "$JOB_RECORD_ROOT"
if [ ! -f "$SUMMARY_TSV" ]; then
  printf 'job_name\tjob_id\tcompute_group\texperiment_name\tsplit_dir\trun_root\n' > "$SUMMARY_TSV"
fi

command="cd ${VC_EDIT_REPO} && \
PYTHON_BIN=${STEPX_PY} \
MODEL_DIR=${MODEL_DIR} \
TOKENIZER_DIR=${TOKENIZER_DIR} \
EDIT_TYPE=${EDIT_TYPE} \
EDIT_INFO=${EDIT_INFO} \
START_INDEX=${START_INDEX} \
LIMIT=${LIMIT} \
GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION} \
MAX_MODEL_LEN=${MAX_MODEL_LEN} \
DTYPE=${DTYPE} \
BATCH_SIZE=${BATCH_SIZE} \
MAX_NUM_SEQS=${MAX_NUM_SEQS} \
TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE} \
MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS} \
KV_CACHE_DTYPE=${KV_CACHE_DTYPE} \
PREPARE_WORKERS=${PREPARE_WORKERS} \
AUDIO_CONDITION_BUILD_WORKERS=${AUDIO_CONDITION_BUILD_WORKERS} \
DISABLE_AUDIO_CONDITION_ITEM_PARALLEL=${DISABLE_AUDIO_CONDITION_ITEM_PARALLEL} \
ASYNC_WRITE_WORKERS=${ASYNC_WRITE_WORKERS} \
ASYNC_VOCODER_WORKERS=${ASYNC_VOCODER_WORKERS} \
PREPARE_BREAKDOWN=${PREPARE_BREAKDOWN} \
NEXT_BATCH_PREFETCH=${NEXT_BATCH_PREFETCH} \
PREFETCH_DEPTH=${PREFETCH_DEPTH} \
USE_ASYNC_ENGINE=${USE_ASYNC_ENGINE} \
STREAM_VOCODE=${STREAM_VOCODE} \
ENGINE_COUNT=${ENGINE_COUNT} \
ENGINE_GPU_GROUPS='${ENGINE_GPU_GROUPS}' \
ENGINE_JOB_SPLIT_MODE='${ENGINE_JOB_SPLIT_MODE}' \
ENGINE_STARTUP_STAGGER_SEC=${ENGINE_STARTUP_STAGGER_SEC} \
ENGINE_PER_ATTEMPT_RETRIES=${ENGINE_PER_ATTEMPT_RETRIES} \
ENGINE_PER_ATTEMPT_BACKOFF_SEC=${ENGINE_PER_ATTEMPT_BACKOFF_SEC} \
PREPROCESS_CACHE_SIZE=${PREPROCESS_CACHE_SIZE} \
AUDIO_DURATION_BUCKETING=${AUDIO_DURATION_BUCKETING} \
DURATION_BUCKET_WINDOW=${DURATION_BUCKET_WINDOW} \
MAX_RUNTIME_SEC=${MAX_RUNTIME_SEC} \
AUDIO_CONDITION_CACHE_DIR=${AUDIO_CONDITION_CACHE_DIR} \
AUDIO_CONDITION_CACHE_WRITEBACK=${AUDIO_CONDITION_CACHE_WRITEBACK} \
COSYVOICE_CUDA_GRAPH=${COSYVOICE_CUDA_GRAPH} \
EDITX_GPU_MONITOR_ENABLE=${EDITX_GPU_MONITOR_ENABLE} \
EDITX_GPU_MONITOR_INTERVAL_SEC=${EDITX_GPU_MONITOR_INTERVAL_SEC} \
DUMMY_GPU_KEEPALIVE=${DUMMY_GPU_KEEPALIVE} \
DUMMY_GPU_KEEPALIVE_DEVICES=${DUMMY_GPU_KEEPALIVE_DEVICES} \
DUMMY_GPU_KEEPALIVE_DTYPE=${DUMMY_GPU_KEEPALIVE_DTYPE} \
DUMMY_GPU_KEEPALIVE_SIZE=${DUMMY_GPU_KEEPALIVE_SIZE} \
DUMMY_GPU_KEEPALIVE_WARMUP=${DUMMY_GPU_KEEPALIVE_WARMUP} \
DUMMY_GPU_KEEPALIVE_SLEEP=${DUMMY_GPU_KEEPALIVE_SLEEP} \
OUTPUT_DIR=${OUTPUT_DIR} \
REPORT_JSONL=${REPORT_JSONL} \
BATCH_METRICS_TSV=${BATCH_METRICS_TSV} \
SUMMARY_JSON=${SUMMARY_JSON} \
GPU_MONITOR_LOG=${GPU_MONITOR_LOG} \
sh ${EDITX_SCRIPT} ${SPLIT_DIR}"

echo "=========================================="
echo "submit editx ablation probe"
echo "  job_name=${JOB_NAME}"
echo "  split_dir=${SPLIT_DIR}"
echo "  experiment_name=${EXPERIMENT_NAME}"
echo "  compute_group=${COMPUTE_GROUP}"
echo "  run_root=${RUN_ROOT}"
echo "  edit=${EDIT_TYPE}:${EDIT_INFO}"
echo "  batch_size=${BATCH_SIZE}"
echo "  max_num_seqs=${MAX_NUM_SEQS}"
echo "  prepare_workers=${PREPARE_WORKERS}"
echo "  audio_condition_build_workers=${AUDIO_CONDITION_BUILD_WORKERS}"
echo "  disable_audio_condition_item_parallel=${DISABLE_AUDIO_CONDITION_ITEM_PARALLEL}"
echo "  async_write_workers=${ASYNC_WRITE_WORKERS}"
echo "  async_vocoder_workers=${ASYNC_VOCODER_WORKERS}"
echo "  prepare_breakdown=${PREPARE_BREAKDOWN}"
echo "  next_batch_prefetch=${NEXT_BATCH_PREFETCH}"
echo "  prefetch_depth=${PREFETCH_DEPTH}"
echo "  use_async_engine=${USE_ASYNC_ENGINE}"
echo "  stream_vocode=${STREAM_VOCODE}"
echo "  engine_count=${ENGINE_COUNT}"
echo "  engine_gpu_groups=${ENGINE_GPU_GROUPS:-auto}"
echo "  engine_job_split_mode=${ENGINE_JOB_SPLIT_MODE}"
echo "  engine_startup_stagger_sec=${ENGINE_STARTUP_STAGGER_SEC}"
echo "  engine_per_attempt_retries=${ENGINE_PER_ATTEMPT_RETRIES}"
echo "  engine_per_attempt_backoff_sec=${ENGINE_PER_ATTEMPT_BACKOFF_SEC}"
echo "  duration_bucketing=${AUDIO_DURATION_BUCKETING}"
echo "  duration_bucket_window=${DURATION_BUCKET_WINDOW}"
echo "  dummy_gpu_keepalive=${DUMMY_GPU_KEEPALIVE}"
echo "  dummy_gpu_keepalive_devices=${DUMMY_GPU_KEEPALIVE_DEVICES:-auto}"
echo "  dummy_gpu_keepalive_size=${DUMMY_GPU_KEEPALIVE_SIZE}"
echo "  dummy_gpu_keepalive_sleep=${DUMMY_GPU_KEEPALIVE_SLEEP}"
echo "  max_runtime_sec=${MAX_RUNTIME_SEC}"
echo "=========================================="

TMP=$(mktemp)
set +e
env -u HTTPS_PROXY -u https_proxy -u HTTP_PROXY -u http_proxy -u ALL_PROXY -u all_proxy \
  "$QZCLI" create-job \
  --name "$JOB_NAME" \
  --command "$command" \
  --workspace "$WORKSPACE" \
  --project "$PROJECT" \
  --compute-group "$COMPUTE_GROUP" \
  --spec "$SPEC" \
  --framework "$FRAMEWORK" \
  --instances "$INSTANCES" \
  --shm "$SHM_GI" \
  --priority "$PRIORITY" \
  --image "$IMAGE" \
  --image-type "$IMAGE_TYPE" >"$TMP" 2>&1
status=$?
set -e
cat "$TMP"
if [ "$status" -ne 0 ]; then
  echo "Submission failed for ${JOB_NAME}"
  grep -q 'Cookie 已过期或无效' "$TMP" && echo "Fix: qzcli login"
  rm -f "$TMP"
  exit "$status"
fi

JOB_ID=$(grep -Eo 'job-[0-9a-fA-F-]{36}' "$TMP" | tail -n 1 || true)
printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
  "$JOB_NAME" "${JOB_ID:-UNKNOWN}" "$COMPUTE_GROUP" "$EXPERIMENT_NAME" "$SPLIT_DIR" "$RUN_ROOT" >> "$SUMMARY_TSV"
rm -f "$TMP"

echo "=========================================="
echo "submitted: ${JOB_NAME}"
echo "  job_id=${JOB_ID:-UNKNOWN}"
echo "  summary_tsv=${SUMMARY_TSV}"
echo "=========================================="
