#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)

SOURCE_ROOT="${SOURCE_ROOT:-/inspire/qb-ilm2/project/embodied-multimodality/public/xyzhang/projects/vc_data_temp/mtd_pass_nonmulti_primary_le_0p3_split_10k}"
ZH_JSONL="${ZH_JSONL:-${SOURCE_ROOT}/zh/zh_slim_0004.jsonl}"
EN_JSONL="${EN_JSONL:-${SOURCE_ROOT}/en/en_slim_0004.jsonl}"

BATCH_ID="${BATCH_ID:-mtdpass-zh0004-en0004-ij-0621-run01}"
RUN_ROOT="${RUN_ROOT:-${ROOT}/outputs/mtd_pass_nonmulti_primary_le_0p3_zh0004_en0004_ij_qz_20260621_run01}"
INPUT_DIR="${INPUT_DIR:-${ROOT}/.qz_vcdata_editx_inputs/${BATCH_ID}}"

mkdir -p "${INPUT_DIR}"
ln -sf "${ZH_JSONL}" "${INPUT_DIR}/$(basename "${ZH_JSONL}")"
ln -sf "${EN_JSONL}" "${INPUT_DIR}/$(basename "${EN_JSONL}")"

echo "[submit-ij] input_dir=${INPUT_DIR}"
echo "[submit-ij] zh_jsonl=${ZH_JSONL} rows=$(wc -l < "${ZH_JSONL}")"
echo "[submit-ij] en_jsonl=${EN_JSONL} rows=$(wc -l < "${EN_JSONL}")"
echo "[submit-ij] run_root=${RUN_ROOT}"
echo "[submit-ij] batch_id=${BATCH_ID}"

QZCLI="${QZCLI:-${ROOT}/scripts/qzcli_with_deps.sh}" \
INPUT_DIR="${INPUT_DIR}" \
RUN_ROOT="${RUN_ROOT}" \
BATCH_ID="${BATCH_ID}" \
FORCE_NEW_BATCH="${FORCE_NEW_BATCH:-1}" \
TASK_COUNT="${TASK_COUNT:-1}" \
JOB_NAME_PREFIX="${JOB_NAME_PREFIX:-xyzhang-mtdpass-ij-vceditx}" \
COMPUTE_GROUP="${COMPUTE_GROUP:-共享h200资源组-3-2机房}" \
COMPUTE_GROUPS_CSV="${COMPUTE_GROUPS_CSV:-共享h200资源组-3-2机房}" \
PRIORITY="${PRIORITY:-10}" \
ZH_TEXT_FIELD="${ZH_TEXT_FIELD:-mtd_transcript}" \
EN_TEXT_FIELD="${EN_TEXT_FIELD:-mtd_transcript}" \
AUDIO_PATH_FIELD="${AUDIO_PATH_FIELD:-audio_path}" \
RUN_PAIRS_ON_QZ="${RUN_PAIRS_ON_QZ:-1}" \
PAIR_LOCAL_DEVICE="${PAIR_LOCAL_DEVICE:-cuda:0}" \
PAIR_LOCAL_RESUME="${PAIR_LOCAL_RESUME:-1}" \
PAIR_LOCAL_PARALLEL="${PAIR_LOCAL_PARALLEL:-1}" \
PAIR_LOCAL_JOBS="${PAIR_LOCAL_JOBS:-6}" \
PAIR_GPU_GUARD_ENABLE="${PAIR_GPU_GUARD_ENABLE:-1}" \
PAIR_GPU_GUARD_GPUS="${PAIR_GPU_GUARD_GPUS:-auto}" \
PAIR_GPU_GUARD_MATRIX_SIZE="${PAIR_GPU_GUARD_MATRIX_SIZE:-8192}" \
PAIR_GPU_GUARD_ACTIVE_MS="${PAIR_GPU_GUARD_ACTIVE_MS:-900}" \
PAIR_GPU_GUARD_IDLE_MS="${PAIR_GPU_GUARD_IDLE_MS:-150}" \
PAIR_GPU_GUARD_DTYPE="${PAIR_GPU_GUARD_DTYPE:-bfloat16}" \
PAIR_GPU_GUARD_RESERVE_MIB="${PAIR_GPU_GUARD_RESERVE_MIB:-0}" \
RUN_IJ_ON_QZ="${RUN_IJ_ON_QZ:-1}" \
IJ_LIMIT="${IJ_LIMIT:-0}" \
IJ_DEVICE="${IJ_DEVICE:-cuda:0}" \
IJ_RUN_SPEED="${IJ_RUN_SPEED:-1}" \
IJ_RUN_PROSODY="${IJ_RUN_PROSODY:-1}" \
IJ_RUN_WAVLM="${IJ_RUN_WAVLM:-1}" \
IJ_RUN_QC="${IJ_RUN_QC:-1}" \
IJ_SPEED_BATCH_SIZE="${IJ_SPEED_BATCH_SIZE:-4}" \
IJ_SPEED_MAX_NUM_SEQS="${IJ_SPEED_MAX_NUM_SEQS:-4}" \
IJ_SPEED_TENSOR_PARALLEL_SIZE="${IJ_SPEED_TENSOR_PARALLEL_SIZE:-8}" \
IJ_SPEED_GPU_MEMORY_UTILIZATION="${IJ_SPEED_GPU_MEMORY_UTILIZATION:-0.75}" \
IJ_SPEED_PREPARE_WORKERS="${IJ_SPEED_PREPARE_WORKERS:-4}" \
IJ_SPEED_AUDIO_CONDITION_BUILD_WORKERS="${IJ_SPEED_AUDIO_CONDITION_BUILD_WORKERS:-4}" \
IJ_SPEED_PREPROCESS_CACHE_SIZE="${IJ_SPEED_PREPROCESS_CACHE_SIZE:-1024}" \
IJ_SEEDVC_SHARDED="${IJ_SEEDVC_SHARDED:-1}" \
IJ_SEEDVC_GPU_IDS="${IJ_SEEDVC_GPU_IDS:-0,1,2,3,4,5,6,7}" \
IJ_SEEDVC_SHARD_COUNT="${IJ_SEEDVC_SHARD_COUNT:-8}" \
IJ_MAX_JOBS="${IJ_MAX_JOBS:-0}" \
IJ_SKIP_EXISTING="${IJ_SKIP_EXISTING:-1}" \
IJ_TIMBRE_PICK="${IJ_TIMBRE_PICK:-random}" \
IJ_SEED="${IJ_SEED:-42}" \
IJ_DIFFUSION_STEPS="${IJ_DIFFUSION_STEPS:-25}" \
IJ_INFERENCE_CFG_RATE="${IJ_INFERENCE_CFG_RATE:-0.7}" \
EDITX_ENGINE_COUNT="${EDITX_ENGINE_COUNT:-16}" \
EDITX_ENGINE_GPU_GROUPS="${EDITX_ENGINE_GPU_GROUPS:-0;0;1;1;2;2;3;3;4;4;5;5;6;6;7;7}" \
EDITX_GPU_MEMORY_UTILIZATION="${EDITX_GPU_MEMORY_UTILIZATION:-0.40}" \
EDITX_BATCH_SIZE="${EDITX_BATCH_SIZE:-6}" \
EDITX_MAX_NUM_SEQS="${EDITX_MAX_NUM_SEQS:-6}" \
EDITX_PREPARE_WORKERS="${EDITX_PREPARE_WORKERS:-4}" \
EDITX_PREPROCESS_CACHE_SIZE="${EDITX_PREPROCESS_CACHE_SIZE:-1024}" \
bash "${ROOT}/submit_vcdata_editx_batch_h200.sh" "$@"
